/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const onMounted: typeof import('vue')['onMounted']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
}
