/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    Auth: typeof import('./components/login/Auth.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Button: typeof import('./components/base/Button.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Input: typeof import('./components/base/Input.vue')['default']
    LoginButtons: typeof import('./components/login/LoginButtons.vue')['default']
    LoginForm: typeof import('./components/login/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
