/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Button: typeof import('./components/base/Button.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Collapse: typeof import('./components/Collapse/index.vue')['default']
    DarkMode: typeof import('./components/DarkMode.vue')['default']
    Drawer: typeof import('./components/drawer/index.vue')['default']
    Dropdown: typeof import('./components/Dropdown/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Hero: typeof import('./components/hero/index.vue')['default']
    HeroFooter: typeof import('./components/hero/HeroFooter.vue')['default']
    HeroImage: typeof import('./components/hero/HeroImage.vue')['default']
    Input: typeof import('./components/base/Input.vue')['default']
    Link: typeof import('./components/base/Link.vue')['default']
    Login: typeof import('./components/login/index.vue')['default']
    LoginForm: typeof import('./components/login/LoginForm.vue')['default']
    LoginGirl: typeof import('./components/LoginGirl.vue')['default']
    OtherLoginWays: typeof import('./components/login/OtherLoginWays.vue')['default']
    RecoverPassword: typeof import('./components/recover-password/index.vue')['default']
    RecoverPasswordForm: typeof import('./components/recover-password/RecoverPasswordForm.vue')['default']
    Register: typeof import('./components/register/index.vue')['default']
    RegisterFooter: typeof import('./components/register/RegisterFooter.vue')['default']
    RegisterForm: typeof import('./components/register/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
